apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: llm-inference
  namespace: argocd
spec:
  description: LLM Inference Stack
  sourceRepos:
    - 'https://github.com/knickkennedy/k8s-llm-inference-stack'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: llm-inference
  source:
    repoURL: https://github.com/knickkennedy/k8s-llm-inference-stack
    targetRevision: HEAD
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
